[package]
name = "sig_recovery_check"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.13.4", features = ["arithmetic", "ecdsa"] }
hex = "0.4"
anyhow = "1.0"
crypto-bigint = "0.5"
serde_json = "1.0"
