x-build-context: &build-context
  context: ../
  dockerfile: integration-test/Dockerfile

x-environment: &common-envs
  MPC_HOME_DIR: /app/data
  RUST_BACKTRACE: full
  RUST_LOG: info

services:
  node0:
    build:
      <<: *build-context
    network_mode: host
    environment:
      <<: *common-envs
    volumes:
      - ../test-configs/0:/app/data
  node1:
    build:
      <<: *build-context
    network_mode: host
    environment:
      <<: *common-envs
    volumes:
      - ../test-configs/1:/app/data
  node2:
    build:
      <<: *build-context
    network_mode: host
    environment:
      <<: *common-envs
    volumes:
      - ../test-configs/2:/app/data
  node3:
    build:
      <<: *build-context
    network_mode: host
    environment:
      <<: *common-envs
    volumes:
      - ../test-configs/3:/app/data
