my_participant_id: 1480181394
participants:
  threshold: 3
  participants:
  - id: 2719987951
    address: 127.0.0.1
    port: 10000
    p2p_public_key: ed25519:33YZ7ggLjJ8ck1tyyxohHooqCGyxgXSW6wFJ7yKBMbr8
  - id: 4271063273
    address: 127.0.0.1
    port: 10001
    p2p_public_key: ed25519:CGkGYBaZYtaYFqgvdktLWsbu75WdvASNyHYoAp66ffBA
  - id: 3961734869
    address: 127.0.0.1
    port: 10002
    p2p_public_key: ed25519:Ba1V1jWYPLqeUhn7GiSAkvmmxxBMVHbbrbKMe17dY8XR
  - id: 1480181394
    address: 127.0.0.1
    port: 10003
    p2p_public_key: ed25519:7BWuGYJQGG5URtPs98kkWiwg3bQUP7v2wLQHyFq7RLVS
p2p_private_key_file: p2p_key
web_ui:
  host: 127.0.0.1
  port: 20003
indexer:
  stream_while_syncing: false
  validate_genesis: true
  sync_mode: Interruption
  concurrency: 1
  mpc_contract_id: test0
  near_credentials_file: validator_key.json
triple:
  concurrency: 4
  desired_triples_to_buffer: 65536
  timeout_sec: 60
  parallel_triple_generation_stagger_time_sec: 1
presignature:
  concurrency: 16
  desired_presignatures_to_buffer: 8192
  timeout_sec: 60
signature:
  timeout_sec: 60
