[package]
name = "mpc-node"
version = "2.0.0-alpha" # DO NOT RELEASE
edition = "2021"

[dependencies]
actix = { workspace = true }
aes-gcm = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
borsh = { workspace = true }
cait-sith = { workspace = true }
clap = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
gcloud-sdk = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
hkdf = { workspace = true }
humantime = { workspace = true }
k256 = { workspace = true }
lazy_static = { workspace = true }
lru = { workspace = true }
near-sdk = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
rand_xorshift = { workspace = true }
rcgen = { workspace = true }
rocksdb = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha3 = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
x509-parser = { workspace = true }

frost-ed25519 = { workspace = true }
curve25519-dalek = { workspace = true }

near-indexer = { workspace = true }
near-indexer-primitives = { workspace = true }
near-client = { workspace = true }
near-config-utils = { workspace = true }
near-crypto = { workspace = true }
near-o11y = { workspace = true }
near-time = { workspace = true }
# todo: update once 1.1.0 is pulbished (though the api did not change)
legacy-mpc-contract = { workspace = true }
mpc-contract = { path = "../libs/chain-signatures/contract/" }

[dev-dependencies]
serial_test = { workspace = true }
reqwest = { workspace = true }
itertools = { workspace = true }
