[package]
name = "mpc-node"
version = "2.0.0-rc.1"
edition = "2021"
license = "MIT"

[dependencies]
actix = { workspace = true }
aes-gcm = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
borsh = { workspace = true }
cait-sith = { workspace = true }
clap = { workspace = true }
dstack-sdk = { git = "https://github.com/Dstack-TEE/dstack.git", tag = "v0.5.2" }
flume = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
gcloud-sdk = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
hkdf = { workspace = true }
humantime = { workspace = true }
k256 = { workspace = true }
lazy_static = { workspace = true }
lru = { workspace = true }
near-sdk = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
rand_xorshift = { workspace = true }
rcgen = { workspace = true }
rocksdb = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha3 = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
x509-parser = { workspace = true }


curve25519-dalek = "4.1.3"
near-indexer = { workspace = true }
near-indexer-primitives = { workspace = true }
near-client = { workspace = true }
near-config-utils = { workspace = true }
near-crypto = { workspace = true }
near-o11y = { workspace = true }
near-time = { workspace = true }

legacy-mpc-contract = { workspace = true }
mpc-contract = { path = "../libs/chain-signatures/contract/", features = [
    "dev-utils",
] }
# Pinned to resolve compilation errors with conflicting implementations of PartialOrd trait
# See error E0283 with multiple impls satisfying `u128: std::cmp::PartialOrd<_>`
deranged = "=0.4.0"


[dev-dependencies]
serial_test = { workspace = true }


reqwest = { workspace = true }
itertools = { workspace = true }
assert_matches = "1.5.0"
mpc-contract = { path = "../libs/chain-signatures/contract/", features = [
    "test-utils",
] }
