[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
async-trait = "0.1.83"
borsh = { version = "1.5.1", features = ["derive"] }
futures = "0.3.31"
futures-util = "0.3.31"
hex = "0.4.3"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread", "sync"] }
tokio-util = "0.7.12"
