[package]
name = "mpc-node"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
aes-gcm = "0.10.3"
anyhow = "1.0.92"
async-trait = "0.1.83"
axum = "0.7.9"
borsh = { version = "1.5.1", features = ["derive"] }
cait-sith = { git = "https://github.com/Near-One/cait-sith.git", features = ["k256"], rev = "75af6bf8c25359dd2be25a838057f3a0dc88f633" }
clap = { version = "4.5.20", features = ["derive", "env"] }
flume = "0.11.1"
futures = "0.3.31"
futures-util = "0.3.31"
hex = { version = "0.4.3", features = ["serde"] }
hex-literal = "0.4.1"
hkdf = "0.12.4"
humantime = "2.1.0"
k256 = "0.13.4"
lazy_static = "1.5.0"
lru = "0.12.5"
near-sdk = "5.2.1"
prometheus = "0.13.4"
rand = "0.8.5"
rand_xorshift = "0.3"
rcgen = "0.13.1"
rocksdb = "0.21.0"
rustls = { version = "0.23.16" }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
sha3 = "0.10.8"
tempfile = "3.14.0"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = "0.7.12"
tokio-rustls = "0.26.1"
tokio-stream = { version = "0.1" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2"
x509-parser = "0.16.0"

# TODO(#82): temporary: rev 274c57e0533453e0f0685984f81998fd72d452ad: includes indexer fixes for single shard tracking.
# Move on to 2.5.0 when the release is cut.
near-indexer = { git = "https://github.com/near/nearcore", rev = "274c57e0533453e0f0685984f81998fd72d452ad" }
near-indexer-primitives = { git = "https://github.com/near/nearcore", rev = "274c57e0533453e0f0685984f81998fd72d452ad" }
near-client = { git = "https://github.com/near/nearcore", rev = "274c57e0533453e0f0685984f81998fd72d452ad" }
near-config-utils = { git = "https://github.com/near/nearcore", rev = "274c57e0533453e0f0685984f81998fd72d452ad" }
near-crypto = { git = "https://github.com/near/nearcore", rev = "274c57e0533453e0f0685984f81998fd72d452ad" }
near-o11y = { git = "https://github.com/near/nearcore", rev = "274c57e0533453e0f0685984f81998fd72d452ad" }

mpc-contract = { git = "https://github.com/near/mpc/", tag = "1.0.0-rc.5" }

[dev-dependencies]
serial_test = "3.2.0"
reqwest = "0.12.9"
