[package]
name = "mpc-node"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
actix-web = "4.9.0"
aes-gcm = "0.10.3"
anyhow = "1.0.92"
async-trait = "0.1.83"
borsh = { version = "1.5.1", features = ["derive"] }
cait-sith = { git = "https://github.com/Near-One/cait-sith.git", features = ["k256"], rev = "75af6bf8c25359dd2be25a838057f3a0dc88f633" }
clap = { version = "4.5.20", features = ["derive", "env"] }
flume = "0.11.1"
futures = "0.3.31"
futures-util = "0.3.31"
hex = { version = "0.4.3", features = ["serde"] }
humantime = "2.1.0"
k256 = "0.13.4"
lazy_static = "1.5.0"
prometheus = "0.13.4"
quinn = "0.11.5"
rand = "0.8.5"
rcgen = "0.13.1"
rocksdb = "0.21.0"
rustls = { version = "0.23.16", default-features = false, features = ["ring"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
tempfile = "3.14.0"
tokio = { version = "1.41.0", features = ["full"] }
tokio-util = "0.7.12"
tokio-stream = { version = "0.1" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
x509-parser = "0.16.0"

near-indexer = { git = "https://github.com/near/nearcore", rev = "2bce389e4fd9273b78e4efbb16fb3317a7389b5b" }
near-indexer-primitives = { git = "https://github.com/near/nearcore", rev = "2bce389e4fd9273b78e4efbb16fb3317a7389b5b" }
near-client = { git = "https://github.com/near/nearcore", rev = "2bce389e4fd9273b78e4efbb16fb3317a7389b5b" }
near-config-utils = { git = "https://github.com/near/nearcore", rev = "2bce389e4fd9273b78e4efbb16fb3317a7389b5b" }
near-o11y = { git = "https://github.com/near/nearcore", rev = "2bce389e4fd9273b78e4efbb16fb3317a7389b5b" }
serial_test = "3.2.0"
