[build-system]
requires = ["setuptools>=60.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nearcore_pytest"
version = "0.1.0"
description = "A wrapper package for nearcore pytest"
requires-python = ">=3.6"

[tool.setuptools]
package-dir = {"" = "../../libs/nearcore/pytest/lib"}
include-package-data = true

