participants:
  threshold: 2
  participants:
    - id: 2719987951
      address: node0
      port: 10000
      p2p_public_key: ed25519:33YZ7ggLjJ8ck1tyyxohHooqCGyxgXSW6wFJ7yKBMbr8
      near_account_id: '2719987951'
    - id: 4271063273
      address: node1
      port: 10001
      p2p_public_key: ed25519:CGkGYBaZYtaYFqgvdktLWsbu75WdvASNyHYoAp66ffBA
      near_account_id: '4271063273'
web_ui:
  host: 0.0.0.0
  port: 20000
triple:
  concurrency: 4
  desired_triples_to_buffer: 65536
  timeout_sec: 60
  parallel_triple_generation_stagger_time_sec: 1
presignature:
  concurrency: 16
  desired_presignatures_to_buffer: 8192
  timeout_sec: 60
signature:
  timeout_sec: 60
validation:
  near:
    threshold: 1
    servers:
      - "https://rpc.mainnet.near.org"
      - "https://rpc.near.org"
      - "https://nearrpc.aurora.dev"
  base:
    threshold: 1
    servers:
      - "http://helios-base:8545"
  eth:
    threshold: 1
    servers:
      - "http://helios-eth:8545"

