x-build-context: &build-context
  context: ../../
  dockerfile: integration-test/Dockerfile

x-environment: &common-envs
  MPC_HOME_DIR: /app/data
  RUST_BACKTRACE: full
  RUST_LOG: info

services:
  node0:
    build:
      <<: *build-context
    environment:
      <<: *common-envs
      MPC_SECRET_STORE_KEY: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      MPC_P2P_PRIVATE_KEY: ed25519:33XCRLaKvqKAfww7XrpY8MFPqgPcEgdEGDaiGVpaGH2SF2Fjb7wtHJv5GCPBiEJkk1D6KH7iPF6xbZ63RRuYWiUG
      MPC_NEAR_ACCOUNT_ID: 2719987951
    ports:
      - "20000:20000"
    volumes:
      - ./0:/app/data
      - ./config.yaml:/app/data/config.yaml
  node1:
    build:
      <<: *build-context
    environment:
      <<: *common-envs
      MPC_SECRET_STORE_KEY: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      MPC_P2P_PRIVATE_KEY: ed25519:5S7diW9n2XfiydnkbzCgGiL5kCT3KQBjcdEjQaSSXdKcGMK9XMoJQZ1N1n3mTvJiWW663eJ48bigLY85HUA9cHA
      MPC_NEAR_ACCOUNT_ID: 4271063273
    ports:
      - "20001:20000"
    volumes:
      - ./1:/app/data
      - ./config.yaml:/app/data/config.yaml
