accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
    "OpenSSL",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true

workarounds = [
    "ring",
    "rustls",
]
