name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  merge_group:
    

jobs:
  ci-tests:
    name: "CI tests"
    runs-on: ubuntu-22.04-8core
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo Clippy
        run: |
          CARGO_TARGET_DIR="target/clippy" \
          RUSTFLAGS="-D warnings" \
          cargo clippy --all-features --all-targets --locked

      - name: Run Cargo fmt
        run: cargo fmt -- --check

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run cargo-nextest
        run: cargo nextest run --release --locked 

      - name: Make sure Docker image can be built
        run: docker build -f integration-test/Dockerfile --progress=plain . 

          