name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  merge_group:
    

jobs:
  ci-tests:
    name: "Run tests"
    runs-on: ubuntu-22.04-8core
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true

      - name: Run Clippy fmt
        run: |
          CARGO_TARGET_DIR="target/clippy" \
          RUSTFLAGS="-D warnings" \
          cargo clippy --all-features --all-targets --locked

      - name: Run Cargo fmt
        run: cargo fmt -- --check
          
      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run cargo-nextest
        run: cargo nextest run --release --locked 

      - name: Build the contract
        run: | 
          cd libs/mpc/chain-signatures
          cargo build -p mpc-contract --target=wasm32-unknown-unknown --release
          cp ../target/wasm32-unknown-unknown/release/mpc_contract.wasm res/mpc_contract.wasm

      - name: Build near core
        run: |
          cd libs/nearcore
          cargo build -p neard

      - name: Build mpc node
        run: cargo build -p mpc-node --release
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup virtualenv
        run: |
          python3 -m venv pytest/venv
          source pytest/venv/bin/activate
          pip install -r libs/nearcore/pytest/requirements.txt

      - name: Run pytest
        run: |
          source pytest/venv/bin/activate
          python3 pytest/index_signature_request.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker image can be built
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: integration-test/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
