name: Docker Build and Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      build-ref:
        default: 'main'
        description: "The branch, tag or SHA to build MPC Docker image from. Default to latest commit on main branch."
        type: string
    

jobs:
  docker-image-build:
    name: "Build and push MPC Docker image"
    runs-on: ubuntu-22.04-8core
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.build-ref }}
        

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Docker image can be built
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: deployment/Dockerfile-gcp
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: nearone/mpc-node-gcp:latest,nearone/mpc-node-gcp:${{ github.event.inputs.build-ref }}-${{ github.sha }}
